name: Docker IGNfab Geoflow bundle base Image

on:
  workflow_dispatch:
    inputs:
      name:
        description: "For what reason ?"
        default: "Testing"
  push:
    branches: [master]
    paths: ['base.dockerfile']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: geoflow-bundle-base
  USER_NAME: ignfab
  VERSION: latest

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    
    # Clone project and recursively get submodules
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    # Get access to Github registry
    - name: Login to the container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./
        file: ./base.dockerfile
        build-args: |
          JOBS=2
          VERSION=${{ env.VERSION }}
        push: true
        tags: ${{ env.REGISTRY }}/${{ env.USER_NAME }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}

