name: build lod22 images

on:
  workflow_dispatch:
    inputs:
      name:
        description: "For what reason ?"
        default: "Testing"
  workflow_run:
    workflows:
    - "build builder image"

env:
  IMAGE_NAME: geoflow-bundle-builder
  USER_NAME: ignfab
  VERSION: latest


jobs:
  build-and-push-images:
    strategy:
      matrix:
        include:
        - dockerfile: lod22-reconstruct.dockerfile
          tags: ignfab/lod22-reconstruct:latest
        - dockerfile: lod22-reconstruct-batch.dockerfile
          tags: ignfab/lod22-reconstruct-batch:latest
        - dockerfile: lod22-reconstruct-stream.dockerfile
          tags: ignfab/lod22-reconstruct-stream:latest


    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:

    # Clone project and recursively get submodules
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Login to the dockerhub registry
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./
        file: ${{ matrix.dockerfile }}
        build-args: |
          JOBS=2
          VERSION=${{ env.VERSION }}
        push: true
        tags: ${{ matrix.tags }}
